# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_Patronymic_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_Patronymic_2.setObjectName("lineEdit_Patronymic_2")
        self.gridLayout_3.addWidget(self.lineEdit_Patronymic_2, 0, 5, 1, 1)
        self.lineEdit_Name_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_Name_2.setObjectName("lineEdit_Name_2")
        self.gridLayout_3.addWidget(self.lineEdit_Name_2, 0, 3, 1, 1)
        self.lineEdit_SurName_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_SurName_2.setObjectName("lineEdit_SurName_2")
        self.gridLayout_3.addWidget(self.lineEdit_SurName_2, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton_Enter = QtWidgets.QPushButton(self.tab)
        self.pushButton_Enter.setObjectName("pushButton_Enter")
        self.gridLayout_3.addWidget(self.pushButton_Enter, 0, 6, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 4, 1, 1)
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setEnabled(False)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEdit_Diastol = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_Diastol.setReadOnly(True)
        self.lineEdit_Diastol.setObjectName("lineEdit_Diastol")
        self.gridLayout_4.addWidget(self.lineEdit_Diastol, 8, 2, 1, 2)
        self.pushButton_BeginMetering = QtWidgets.QPushButton(self.frame)
        self.pushButton_BeginMetering.setObjectName("pushButton_BeginMetering")
        self.gridLayout_4.addWidget(self.pushButton_BeginMetering, 1, 0, 1, 1)
        self.lineEdit_Pulse = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_Pulse.setReadOnly(True)
        self.lineEdit_Pulse.setObjectName("lineEdit_Pulse")
        self.gridLayout_4.addWidget(self.lineEdit_Pulse, 6, 2, 1, 2)
        self.label_Date = QtWidgets.QLabel(self.frame)
        self.label_Date.setObjectName("label_Date")
        self.gridLayout_4.addWidget(self.label_Date, 4, 0, 1, 1)
        self.label_Systol = QtWidgets.QLabel(self.frame)
        self.label_Systol.setObjectName("label_Systol")
        self.gridLayout_4.addWidget(self.label_Systol, 7, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 1, 2, 1, 1)
        self.label_Temperature = QtWidgets.QLabel(self.frame)
        self.label_Temperature.setObjectName("label_Temperature")
        self.gridLayout_4.addWidget(self.label_Temperature, 5, 0, 1, 1)
        self.label_Pulse = QtWidgets.QLabel(self.frame)
        self.label_Pulse.setObjectName("label_Pulse")
        self.gridLayout_4.addWidget(self.label_Pulse, 6, 0, 1, 1)
        self.lineEdit_Systol = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_Systol.setReadOnly(True)
        self.lineEdit_Systol.setObjectName("lineEdit_Systol")
        self.gridLayout_4.addWidget(self.lineEdit_Systol, 7, 2, 1, 2)
        self.lineEdit_Temperature = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_Temperature.setReadOnly(True)
        self.lineEdit_Temperature.setObjectName("lineEdit_Temperature")
        self.gridLayout_4.addWidget(self.lineEdit_Temperature, 5, 2, 1, 2)
        self.lineEdit_Date = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_Date.setReadOnly(True)
        self.lineEdit_Date.setObjectName("lineEdit_Date")
        self.gridLayout_4.addWidget(self.lineEdit_Date, 4, 2, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 10, 2, 1, 1)
        self.label_Diastol = QtWidgets.QLabel(self.frame)
        self.label_Diastol.setObjectName("label_Diastol")
        self.gridLayout_4.addWidget(self.label_Diastol, 8, 0, 1, 1)
        self.label_Time = QtWidgets.QLabel(self.frame)
        self.label_Time.setObjectName("label_Time")
        self.gridLayout_4.addWidget(self.label_Time, 3, 0, 1, 1)
        self.lineEdit_Time = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_Time.setReadOnly(True)
        self.lineEdit_Time.setObjectName("lineEdit_Time")
        self.gridLayout_4.addWidget(self.lineEdit_Time, 3, 2, 1, 2)
        self.pushButton_AddRecord = QtWidgets.QPushButton(self.frame)
        self.pushButton_AddRecord.setObjectName("pushButton_AddRecord")
        self.gridLayout_4.addWidget(self.pushButton_AddRecord, 9, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame, 1, 0, 1, 7)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_Patronymic = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_Patronymic.setObjectName("lineEdit_Patronymic")
        self.gridLayout_2.addWidget(self.lineEdit_Patronymic, 0, 5, 1, 1)
        self.label_Surname = QtWidgets.QLabel(self.tab_2)
        self.label_Surname.setObjectName("label_Surname")
        self.gridLayout_2.addWidget(self.label_Surname, 0, 0, 1, 1)
        self.lineEdit_SurName = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_SurName.setObjectName("lineEdit_SurName")
        self.gridLayout_2.addWidget(self.lineEdit_SurName, 0, 1, 1, 1)
        self.label_Name = QtWidgets.QLabel(self.tab_2)
        self.label_Name.setObjectName("label_Name")
        self.gridLayout_2.addWidget(self.label_Name, 0, 2, 1, 1)
        self.pushButton_Show = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_Show.setObjectName("pushButton_Show")
        self.gridLayout_2.addWidget(self.pushButton_Show, 0, 6, 1, 1)
        self.lineEdit_Name = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_Name.setObjectName("lineEdit_Name")
        self.gridLayout_2.addWidget(self.lineEdit_Name, 0, 3, 1, 1)
        self.label_Patronymic = QtWidgets.QLabel(self.tab_2)
        self.label_Patronymic.setObjectName("label_Patronymic")
        self.gridLayout_2.addWidget(self.label_Patronymic, 0, 4, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideRight)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(120)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.gridLayout_2.addWidget(self.tableWidget, 1, 0, 1, 7)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.action_Qt = QtWidgets.QAction(MainWindow)
        self.action_Qt.setObjectName("action_Qt")
        self.action_AboutProgram = QtWidgets.QAction(MainWindow)
        self.action_AboutProgram.setObjectName("action_AboutProgram")
        self.action_SaveDB = QtWidgets.QAction(MainWindow)
        self.action_SaveDB.setObjectName("action_SaveDB")
        self.action_LoadDB = QtWidgets.QAction(MainWindow)
        self.action_LoadDB.setObjectName("action_LoadDB")
        self.action_Exit = QtWidgets.QAction(MainWindow)
        self.action_Exit.setObjectName("action_Exit")
        self.action_Settings = QtWidgets.QAction(MainWindow)
        self.action_Settings.setObjectName("action_Settings")
        self.menu.addAction(self.action_SaveDB)
        self.menu.addAction(self.action_LoadDB)
        self.menu.addSeparator()
        self.menu.addAction(self.action_Settings)
        self.menu.addSeparator()
        self.menu.addAction(self.action_Exit)
        self.menu_2.addAction(self.action_Qt)
        self.menu_2.addAction(self.action_AboutProgram)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Фамилия"))
        self.pushButton_Enter.setText(_translate("MainWindow", "Вход"))
        self.label_2.setText(_translate("MainWindow", "Имя"))
        self.label_3.setText(_translate("MainWindow", "Отчество"))
        self.pushButton_BeginMetering.setText(_translate("MainWindow", "Начать измерение"))
        self.label_Date.setText(_translate("MainWindow", "Дата"))
        self.label_Systol.setText(_translate("MainWindow", "Систолическое давление"))
        self.label_Temperature.setText(_translate("MainWindow", "Температура"))
        self.label_Pulse.setText(_translate("MainWindow", "Пульс"))
        self.label_Diastol.setText(_translate("MainWindow", "Диастолическое давление"))
        self.label_Time.setText(_translate("MainWindow", "Время"))
        self.pushButton_AddRecord.setText(_translate("MainWindow", "Добавить запись"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Снятие показаний"))
        self.label_Surname.setText(_translate("MainWindow", "Фамилия"))
        self.label_Name.setText(_translate("MainWindow", "Имя"))
        self.pushButton_Show.setText(_translate("MainWindow", "Отобразить"))
        self.label_Patronymic.setText(_translate("MainWindow", "Отчество"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Дата"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Время"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Температура"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Пульс"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Cист давление"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Диас давление"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Просмотр данных"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.menu_2.setTitle(_translate("MainWindow", "Справка"))
        self.action_Qt.setText(_translate("MainWindow", "О Qt"))
        self.action_AboutProgram.setText(_translate("MainWindow", "О программе"))
        self.action_SaveDB.setText(_translate("MainWindow", "Сохранить БД"))
        self.action_LoadDB.setText(_translate("MainWindow", "Загрузить БД"))
        self.action_Exit.setText(_translate("MainWindow", "Выход"))
        self.action_Settings.setText(_translate("MainWindow", "Настройки"))
